# =============================================================================
# GOLANGCI-LINT CONFIGURATION (v1 format)
# =============================================================================
#
# This configuration enables linters that help maintain code quality.
# Run locally: golangci-lint run
# Run with fixes: golangci-lint run --fix
#
# NOTE: We start with lenient settings to avoid blocking CI on existing code.
#
# =============================================================================

run:
  timeout: 5m
  skip-dirs:
    - api/proto/gen
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: api/proto/gen/
      linters:
        - all
